[package]
name = "beatrix_core"
version = "0.1.0"
authors = ["Anit Nilay <anit.nilay20@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "3.5.1", optional = true }
serde = "1.0.119"
async-trait = "0.1.42"
thiserror = "2.0.18"
futures = "0.3"
syn = { version = "2.0.115" }
tokio = { version = "1.49.0", features = ["full"] }
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "postgres",
  "chrono"
], optional = true }
chrono = { version = "0.4.43", optional = true }

[features]
default = ["postgres"]
postgres = ["dep:sqlx", "sqlx/postgres"]
chrono = ["dep:chrono", "sqlx/chrono"]

#mongo
mongo = ["dep:mongodb"]
